server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true    #是否向注册中心注册自己
    fetch-registry: true    #是否从注册中心抓取已有的注册信息，默认true，集群必须设置为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true   #访问路径可以显示IP地址
#    Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
#    lease-renewal-interval-in-seconds: 1
#    Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2