server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: false  #不注册进eureka服务中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以 debug 级别监控 com.chen.service.PaymentFeignService 接口
    com.chen.service.PaymentFeignService: debug
